version: '3.8'

services:
  backend:
    container_name: us-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    environment:
      - AIR_WATCH_DELAY=1000
    depends_on:
      - frontend

  frontend:
    container_name: us-frontend
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vite-project:/app
      - node_modules:/app/node_modules
    tty: true

volumes:
  node_modules: {}
