# .air.toml

# Configurations
[build]
cmd = "go build -o ./tmp/main cmd/main.go"
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "node_modules", "tmp", "dist"]  # Exclude db directory
watch_dir = ["./", "./cmd", "./db"]  # Watch db directory
delay = 1000
stop_on_modify = true

 
[log]
# Log levels: debug, info, warn, error, fatal, panic
level = "debug"


[run]
# Command to run the binary
cmd = "./cmd/app"

# Directory to watch for changes
watch_dir = ["./cmd", "./pkg"]

# Patterns to ignore (glob)
exclude_dir = ["vendor"]

# Files to watch for changes
include_ext = ["go"]

# Files to ignore
exclude_file = []

# Delay before restarting after a change (in milliseconds)
delay = 1000

# Logging settings
log_level = "info"
log_color = "true"
log_time = "true"
